CREATE TABLESPACE hospital_db
  DATAFILE 'project.dat' 
    SIZE 20M
  ONLINE;

CREATE TEMPORARY TABLESPACE hospital_temp
  TEMPFILE 'project_tempfile.dbf'
    SIZE 5M
    AUTOEXTEND ON;
    
CREATE USER HOSPITAL
  IDENTIFIED BY Password1
  DEFAULT TABLESPACE hospital_db
  TEMPORARY TABLESPACE hospital_temp
  QUOTA 20M on hospital_db;
  
  DROP TABLE HOSPITAL.PATIENT;
  
  CREATE TABLE HOSPITAL.PATIENT (
    "PATIENT_ID" NUMBER(6, 0) CONSTRAINT "PAT_PK" PRIMARY KEY,
    "FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(25 BYTE) CONSTRAINT "PAT_LAST_NAME_NN" NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(25 BYTE) CONSTRAINT "PAT_EMAIL_NN" NOT NULL ENABLE, 
	"PHONE_NUMBER" VARCHAR2(20 BYTE));
    
    CREATE TABLE STAY (
    "ADMISSION_ID" NUMBER(8, 0),
    "START_DATE" DATE DEFAULT (sysdate),  
    "END_DATE"  DATE CONSTRAINT "ADM_END_DATE_NN" NOT NULL ENABLE,
	"ROOM_ID" NUMBER(5, 0) CONSTRAINT "ROOM_NN" NOT NULL ENABLE, 
	"PATIENT_ID" NUMBER(6, 0) CONSTRAINT "PAT_FK" REFERENCES
            HOSPITAL.PATIENT(PATIENT_ID));


