-- Sample patient data
-- Author: eoin.keady@gmail.com
-- Date: 02-Dec-2017

INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES ('Yoshio','Mcclain','nonummy.ipsum@Uttincidunt.co.uk','2372267068');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Edward','Contreras','interdum.enim.non@mi.ca','5088962901');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES ('Abel','Deleon','Sed@gravidaAliquamtincidunt.edu','0095779323');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Joseph','Harrison','urna@mieleifend.net','8259851450');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Tad','Mccormick','nunc.interdum@Integereu.net','6786587375');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Rahim','Hansen','lectus.ante@dignissim.co.uk','3747825237');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Acton','Burns','ut@Sedetlibero.org','8914350038');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES ('Raymond','Keller','vitae@aliquam.net','8131191908');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Amery','Walters','odio.vel@nascetur.ca','8225611297');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES ('Kareem','Barron','mollis@tempusnonlacinia.edu','7293491720');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Dillon','Oconnor','Donec.at@veliteu.org','3424033536');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Hakeem','Lowe','et.ultrices@Nuncsed.com','8488261461');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Duncan','England','euismod@Phasellusdapibus.net','3402487007');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Ferdinand','Cross','in.tempus@parturient.com','9081180417');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Ashton','Ward','Phasellus.fermentum.convallis@sitametdiam.com','8518277632');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Justin','Small','est.ac.facilisis@tortorNunc.co.uk','4692258576');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Joel','Guthrie','neque.non.quam@Phasellus.com','5105140800');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('August','Singleton','Suspendisse.dui@aauctor.edu','7549753135');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Grant','Morrow','diam@nonlorem.co.uk','2388360146');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES ('Samson','Marquez','sagittis.semper@nec.co.uk','7490040670');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Chandler','Weaver','nisi.dictum@enimnisl.com','5402653957');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Ferris','Noel','tristique.pellentesque.tellus@Phasellusdapibus.ca','7664896091');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Brandon','Preston','tellus.Aenean.egestas@purusgravida.org','4623982983');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Joseph','Cotton','eu.neque.pellentesque@justoeuarcu.net','8749248924');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('John','Boyd','at@risusDuisa.org','9003058328');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Jameson','Montgomery','sollicitudin.adipiscing.ligula@dictumsapien.ca','8592474375');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Reece','Duke','ut.lacus.Nulla@duiSuspendisseac.ca','4092307999');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Carl','French','dui.Cras@eget.com','5313585600');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Hyatt','Crosby','non.magna.Nam@elementumsem.edu','5612563529');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES ('William','Shepard','ipsum@augueSedmolestie.net','0535872269');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Duncan','Farrell','sit@egestasligulaNullam.org','5664978388');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Barclay','Landry','dictum.Proin@idsapienCras.co.uk','1743574604');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Talon','Salazar','aliquet@Nullaaliquet.net','3706201197');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Howard','Donaldson','tellus.eu.augue@ultricessit.org','4777016924');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Griffith','Lee','Aenean@sedhendrerit.net','4416931961');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Yoshio','Mcdaniel','accumsan@ligulaconsectetuer.edu','3657582849');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Cedric','Pope','ligula@In.net','7082545158');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Kato','Moss','magnis.dis@magnisdisparturient.com','8725430557');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Dean','Gilbert','ut@eleifend.ca','2491496124');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Isaiah','Schneider','lorem.eget.mollis@felisNullatempor.com','0010331374');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Beck','Carney','suscipit@Loremipsum.ca','0734949313');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Amery','Schultz','Sed.nec.metus@aliquamadipiscinglacus.net','8777051425');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Nathaniel','Gomez','augue.porttitor.interdum@neque.ca','7035234833');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Wyatt','Rodgers','ligula.eu@convallis.net','5235341458');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Ciaran','England','massa.Vestibulum.accumsan@consequatenim.com','2798987103');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Murphy','Snider','ac.feugiat@pharetraut.org','0458723101');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Paul','Dunn','Cras.vulputate.velit@eratsemperrutrum.ca','5206608297');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Tyler','Barnett','scelerisque.dui.Suspendisse@seddolor.co.uk','5433525224');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES ('Laith','Hunter','malesuada.vel.venenatis@sem.com','4090829592');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Noah','Lynn','In@Vestibulumaccumsanneque.edu','1476180083');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Zeph','Griffin','Nam@litoratorquentper.net','5243236045');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Dean','Daniels','laoreet@euismod.ca','9732034052');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Lucas','Raymond','auctor.nunc.nulla@scelerisqueloremipsum.co.uk','4091491544');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Finn','Paul','rhoncus.id.mollis@dui.net','3139194210');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Jason','Mcneil','est.Nunc@tortor.org','6612216320');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Yoshio','Vargas','Vivamus.sit@aodio.org','5083685224');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Jerry','Summers','nec@inmagna.ca','7069910046');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Travis','Guy','Mauris@Integereulacus.edu','0946530389');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES ('Vance','Wallace','ante.ipsum@convallis.org','1154076789');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Avram','Camacho','magna.a.neque@Pellentesquetincidunt.edu','7328775590');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Mufutau','Mcdaniel','ac.mattis.velit@mattisInteger.org','6954767541');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Colorado','Burke','eu@CuraePhasellusornare.net','4823812394');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Jacob','Cortez','Nunc.mauris.elit@magna.org','5259232946');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Garth','Stephenson','mus.Proin@dictum.edu','2911351263');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Elmo','Dennis','Proin.vel@Vestibulumante.edu','4202451876');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Driscoll','Myers','quis@variusorciin.ca','6515329992');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Prescott','Burke','neque@id.net','0499538694');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Rigel','Rhodes','mollis.Phasellus@imperdietnec.org','8663780558');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES ('Palmer','Dorsey','amet.consectetuer@Fuscediam.net','6017966002');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Patrick','Blackburn','at.augue.id@Morbiaccumsan.com','5031413854');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Jerry','Hudson','justo.eu.arcu@fringillacursus.com','8027280556');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Ignatius','Riggs','penatibus.et.magnis@augueid.com','1238774412');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Declan','Ortiz','erat.neque.non@Nuncquis.co.uk','6419935008');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Dean','Dodson','Nunc.mauris@nasceturridiculus.ca','4606089058');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Hall','Olsen','volutpat.ornare@consectetuer.com','1821737965');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Jonas','Morrison','venenatis.a@facilisisvitaeorci.edu','9036322261');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Hiram','Ayala','montes@lobortistellus.org','6319922681');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Harrison','Bauer','Morbi.accumsan.laoreet@massaSuspendisse.net','6908586673');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES ('Tobias','Shaw','dui.nec.tempus@antebibendum.org','2725621665');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Elmo','Buckner','penatibus.et@euismodindolor.ca','1913782739');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Blake','Hooper','metus@variusNamporttitor.edu','2058460763');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Malcolm','Rutledge','elit.Nulla.facilisi@est.edu','0246659036');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Kirk','Foley','venenatis.lacus@mattisCraseget.com','4329548963');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Chase','Nunez','neque.pellentesque@Praesent.com','1014284873');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Daquan','Vance','a.dui@semperNam.net','3759020913');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Kyle','Puckett','lorem.ut@Aeneaneuismod.ca','9030681560');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Armando','Abbott','non@sollicitudinadipiscing.co.uk','4543828482');
INSERT INTO hospital.patient (first_name,last_name,email,phone_number) VALUES('Griffith','Harrison','nunc@lectusconvallisest.ca','5398956759');

