insert into hospital.drug (DRUG_NAME) values('Panadol');
insert into hospital.drug (DRUG_NAME) values('Nurofen');
insert into hospital.drug (DRUG_NAME) values('Solpadine');
insert into hospital.drug (DRUG_NAME) values('Valium');
insert into hospital.drug (DRUG_NAME) values('Lemsip');
insert into hospital.drug (DRUG_NAME) values('Oxygen');
insert into hospital.drug (DRUG_NAME) values('Antibiotics');
insert into hospital.drug (DRUG_NAME) values('Betnesol');
insert into hospital.drug (DRUG_NAME) values('Bonviva');
insert into hospital.drug (DRUG_NAME) values('Sodium');
insert into hospital.drug (DRUG_NAME) values('Calcium');

insert into hospital.ward (ward_name) values('Oncology');
insert into hospital.ward (ward_name) values('Radiotherapy');
insert into hospital.ward (ward_name) values('Pediatric');
insert into hospital.ward (ward_name) values('Nutrition');
insert into hospital.ward (ward_name) values('Dermatology');
insert into hospital.ward (ward_name) values('Orthopaedic');
insert into hospital.ward (ward_name) values('Neurology');
insert into hospital.ward (ward_name) values('Microbology');
insert into hospital.ward (ward_name) values('Critical Care');
insert into hospital.ward (ward_name) values('Cardiology');
insert into hospital.ward (ward_name) values('ENT');
